---
# Because of that error: The checksum parameter has to be in format <algorithm>:<checksum>
# I had to specify 2 times with condition. It would be nice if it was possible to do it once.
- name: downloading deb file {{ url_path }}/{{ deb_file }} with checksum check
  get_url:
    url: "{{ url_path }}/{{ deb_file }}"
    dest: /tmp/{{ deb_file }}
    checksum: "{{ deb_checksum }}"
  when: deb_checksum is defined 

- name: downloading deb file {{ url_path }}/{{ deb_file }} no checksum
  get_url:
    url: "{{ url_path }}/{{ deb_file }}"
    dest: /tmp/{{ deb_file }}
  when: deb_checksum is not defined 
  
    
    # steps taken from http://code.visualstudio.com/docs/setup/linux#_common-questions
# It turned out deb option is fully equivalent to: 1) dpkg -i /tmp/{{ deb_file }} 2) sudo apt-get install -f -y   
- name: debian package install
  apt:
    deb: /tmp/{{ deb_file }}
  become: yes


  